apiVersion: monitoring.coreos.com/v1alpha1
kind: PrometheusAgent
metadata:
  name: prometheus-agent
  namespace: monitoring
spec:
  image: quay.io/prometheus/prometheus:v3.5.0
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  podMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  podMonitorSelector: {}
  scrapeConfigSelector: {}
  resources:
    requests:
      memory: 400Mi
  securityContext:
    fsGroup: 2000
    runAsNonRoot: true
    runAsUser: 1000
  serviceAccountName: prometheus-k8s
  serviceMonitorNamespaceSelector: {}
  serviceMonitorSelector: {}
  version: 2.47.0
  remoteWrite:
  - url: "http://prometheus-k8s.monitoring.svc.cluster.local:9090/api/v1/write"
    name: "dev"
    tlsConfig:
      insecureSkipVerify: true
  externalLabels:
    cluster: dev
  replicaExternalLabelName: "dev"


