apiVersion: v1
kind: Service
metadata:
  annotations:
    service.cilium.io/global: "true"
  labels:
    app.kubernetes.io/name: prometheus
    app.kubernetes.io/instance: k8s
  name: prometheus-k8s
  namespace: monitoring
spec:
  ports:
  - name: web
    port: 9090
    targetPort: web
  - name: reloader-web
    port: 8080
    targetPort: reloader-web
  selector:
    app.kubernetes.io/instance: k8s
  sessionAffinity: ClientIP
